runtime: python37

# We'll need to fool around to find the optimal instance_class and max_concurrent_requests
instance_class: F1
automatic_scaling:
  max_concurrent_requests: 10 # default

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
